### ISSUE TITLE
Inconsistent spacing on home page

### ISSUE THREAD

**Issue by StefanTobler** [StefanTobler/stefantobler.github.io#6]

**Comment by StefanTobler** [comment]
Decided to keep the spacing, because left align is a bit too harsh. 

The source is in `style.css`.
```css
.card-body {
  text-align: justify;
}
```
